In [64]:
import requests
import pandas as pd
import os

def nba_teams_salary(year: int):
    url = f'https://www.hoopshype.com/salaries/teams/?season={year}'
    response = requests.get(url)
    tables = pd.read_html(response.text)
    df = tables[0]
    df.rename(columns={df.columns[0]: 'years'}, inplace=True)
    df.rename(columns={df.columns[1]: 'team'}, inplace=True)
    df.rename(columns={df.columns[2]: 'total_salary'}, inplace=True)
    df['years'] = year 
    df['total_salary'] = df['total_salary'].str.replace('$', '', regex=False).str.replace(',', '', regex=False)
    if year == 2025:
        df.drop(df.columns[3:6], axis=1, inplace=True)
    
    return df


# df['year'] = new_data
# df = tables[0]

In [65]:
nba_teams_salary(2025)

/tmp/ipykernel_90850/193190064.py:8: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text)

    years           team total_salary
0    2025      Cavaliers    228898634
1    2025      Mavericks    211579121
2    2025         Knicks    205444377
3    2025       Clippers    205218523
4    2025        Celtics    204311991
5    2025   Timberwolves    203531887
6    2025         Lakers    201185155
7    2025        Rockets    201150043
8    2025          Magic    197122456
9    2025        Raptors    196520970
10   2025        Nuggets    194790301
11   2025           Suns    193123086
12   2025          76ers    191750451
13   2025       Pelicans    190982633
14   2025        Thunder    190199275
15   2025           Heat    188690973
16   2025  Trail Blazers    187731067
17   2025          Spurs    187183460
18   2025          Hawks    186584161
19   2025          Kings    186063825
20   2025         Pacers    183742674
21   2025        Hornets    180776048
22   2025          Bucks    176698323
23   2025      Grizzlies    174303544
24   2025        Pistons    170909241
25   2025       Warriors    168921159
26   2025        Wizards    157575777
27   2025          Bulls    153730899
28   2025           Jazz    152746679
29   2025           Nets    133312610

In [19]:
import urllib.request as req
import os
import bs4 as bs
import pandas as pd

def nba_teams_advancedstate(year:int):

    url = f"https://www.basketball-reference.com/leagues/NBA_{year}.html"
    resp = req.urlopen(url)
    content = resp.read()
    html = bs.BeautifulSoup(content,'html.parser')

    table = html.find("div", {"id": "all_advanced_team"}).find("tbody")
    rows = table.find_all("tr")

    teams = []
    team_seen = set()

    for row in rows:
        # 跳過空列或是有 'class=thead' 的分隔列
        if row.get("class") == ['thead']:
            continue

        # 抓球員名字與隊伍代碼
        team_cell = row.find("td", {"data-stat": "team"})
        age_cell = row.find("td", {"data-stat": "age"})
        wins_cell = row.find("td", {"data-stat": "wins"})
        losses_cell = row.find("td", {"data-stat": "losses"})
        wins_pyth_cell = row.find("td", {"data-stat": "wins_pyth"})
        losses_pyth_cell = row.find("td", {"data-stat": "losses_pyth"})
        mov_cell = row.find("td", {"data-stat": "mov"})
        sos_cell = row.find("td", {"data-stat": "sos"})
        srs_cell = row.find("td", {"data-stat": "srs"})
        off_rtg_cell = row.find("td", {"data-stat": "off_rtg"})
        def_rtg_cell = row.find("td", {"data-stat": "def_rtg"})
        net_rtg_cell = row.find("td", {"data-stat": "net_rtg"})
        pace_cell = row.find("td", {"data-stat": "pace"})
        fta_per_fga_pct_cell = row.find("td", {"data-stat": "fta_per_fga_pct"})
        fg3a_per_fga_pct_cell = row.find("td", {"data-stat": "fg3a_per_fga_pct"})
        ts_pct_cell = row.find("td", {"data-stat": "ts_pct"})
        efg_pct_cell = row.find("td", {"data-stat": "efg_pct"})
        tov_pct_cell = row.find("td", {"data-stat": "tov_pct"})
        orb_pct_cell = row.find("td", {"data-stat": "orb_pct"})
        ft_rate_cell = row.find("td", {"data-stat": "ft_rate"})
        opp_efg_pct_cell = row.find("td", {"data-stat": "opp_efg_pct"})
        opp_tov_pct_cell = row.find("td", {"data-stat": "opp_tov_pct"})
        drb_pct_cell = row.find("td", {"data-stat": "drb_pct"})
        opp_ft_rate_cell = row.find("td", {"data-stat": "opp_ft_rate"})
        arena_name_cell = row.find("td", {"data-stat": "arena_name"})
        attendance_cell = row.find("td", {"data-stat": "attendance"})
        attendance_per_g_cell = row.find("td", {"data-stat": "attendance_per_g"})


        team = team_cell.text.strip()
        age = age_cell.text.strip()
        wins = wins_cell.text.strip()
        losses = losses_cell.text.strip()
        wins_pyth = wins_pyth_cell.text.strip()
        losses_pyth = losses_pyth_cell.text.strip()
        mov = mov_cell.text.strip()
        sos = sos_cell.text.strip()
        srs = srs_cell.text.strip()
        off_rtg = off_rtg_cell.text.strip()
        def_rtg = def_rtg_cell.text.strip()
        net_rtg = net_rtg_cell.text.strip()
        pace = pace_cell.text.strip()
        fta_per_fga_pct = fta_per_fga_pct_cell.text.strip()
        fg3a_per_fga_pct = fg3a_per_fga_pct_cell.text.strip()
        ts_pct = ts_pct_cell.text.strip()
        efg_pct = efg_pct_cell.text.strip()
        tov_pct = tov_pct_cell.text.strip()
        orb_pct = orb_pct_cell.text.strip()
        ft_rate = ft_rate_cell.text.strip()

        opp_efg_pct = opp_efg_pct_cell.text.strip()
        opp_tov_pct = opp_tov_pct_cell.text.strip()
        drb_pct = drb_pct_cell.text.strip()
        opp_ft_rate = opp_ft_rate_cell.text.strip()

        arena_name = arena_name_cell.text.strip()
        attendance = attendance_cell.text.strip()
        attendance_per_g = attendance_per_g_cell.text.strip()



        if team not in team_seen:
            teams.append({
                "year": year,
                "team": team,
                "average_age": age,
                "wins": wins,
                "loses": losses,
                "pythagorean_wins": wins_pyth,
                "pythagorean_lose": losses_pyth,
                "margin_of_victory": mov,
                "strength_of_schedule": sos,
                "simple_rating_system": srs,
                "offensive_rating": off_rtg,
                "defensive_rating": def_rtg,
                "net_rating": net_rtg,
                "pace_factor": pace,
                "free_throw_attempt_rate": fta_per_fga_pct,
                "3p_attempt_rate": fg3a_per_fga_pct,
                "true_shooting_percentage": ts_pct,
                "effective_field_goal_percentage": efg_pct,
                "turnover_percentage": tov_pct,
                "offensive_rebound_percentage": orb_pct,
                "free_throws_per_field_goal_attempt": ft_rate,

                "opponent_effective_field_goal_percentage": opp_efg_pct,
                "opponent_turnover_percentage": opp_tov_pct,
                "defensive_rebound_percentage": drb_pct,
                "opponent_free_throws_per_field_goal_attempt": opp_ft_rate,

                "arena_name": arena_name,
                "attendance": attendance,
                "attendance_per_g": attendance_per_g,

                })
            team_seen.add(team)

    # dirname = "nba_teams_advancedstate"
    # if not os.path.exists(dirname):
    #     os.mkdir(dirname)


    df = pd.DataFrame(teams)
    df['team'] = df['team'].str.replace('*', '', regex=False)
    df['team_cut'] = df["team"].str.split(' ')
    df['team'] = df['team_cut'].str[-1]
    df.drop(columns=['team_cut'], inplace=True)
    df.index += 1
    # fn = os.path.join(dirname, f"nba_teams_advancedstate_{year}.csv")
    # df.to_csv(fn, encoding="utf-8-sig")

    return df

In [ ]:
nba_teams_advancedstate(2024)

In [22]:
import urllib.request as req
import bs4 as bs
import pandas as pd
import os
import time
import random


def nba_players_salary(year):

    team_inf = {
        'atlanta-hawks': [1],
        'boston-celtics': [2],
        'brooklyn-nets': [17],
        'charlotte-hornets': [5312],
        'chicago-bulls': [4],
        'cleveland-cavaliers': [5],
        'dallas-mavericks': [6],
        'denver-nuggets': [7],
        'detroit-pistons': [8],
        'golden-state-warriors': [9],
        'houston-rockets': [10],
        'indiana-pacers': [11],
        'los-angeles-clippers': [12],
        'los-angeles-lakers': [13],
        'memphis-grizzlies': [29],
        'miami-heat': [14],
        'milwaukee-bucks': [15],
        'minnesota-timberwolves': [16],
        'new-orleans-pelicans': [3],
        'new-york-knicks': [18],
        'oklahoma-city-thunder': [25],
        'orlando-magic': [19],
        'philadelphia-76ers': [20],
        'phoenix-suns': [21],
        'portland-trail-blazers': [22],
        'sacramento-kings': [23],
        'san-antonio-spurs': [24],
        'toronto-raptors': [28],
        'utah-jazz': [26],
        'washington-wizards': [27]
    }

    all_rows = []

    for team_name, url_num in team_inf.items():

        url = f"https://www.hoopshype.com/salaries/teams/{team_name}/{url_num[0]}/?season={year}"
        print(url)

        # 儲存的路徑
        # dirname = os.path.join('.', 'salary')
        # if not os.path.exists(dirname):
        #     os.makedirs(dirname)

        # 取得網頁內容
        r = req.Request(url)
        r.add_header('user-agent',
                    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/1')

        # 開啟網址並讀取html內容
        resp = req.urlopen(r)
        content = resp.read()
        html = bs.BeautifulSoup(content)


        # players
        players = html.find_all('td', {"class": "vTd-Ji__vTd-Ji"})
        player_list = []
        for player in players:
            player_list.append(player.text)
        player_list = player_list[:-1]
        # player_list[-1] = 'total'

        # salary
        year_items = html.find_all('th', {"colspan": "1", "class": "RLrCiX__RLrCiX"})
        salaryAll = html.find_all('td', {"class": "RLrCiX__RLrCiX"})
        salary_list = []
        for salary in salaryAll:
            salary_list.append(int(salary.text.strip()[1:].replace(',', '')))
        salary_list = salary_list[:-len(year_items)][::len(year_items)]


        # 檢查 player / salary 數量一致
        try:
            if len(player_list) != len(salary_list):
                raise ValueError(
                    f"[資料不一致] {year} 年 {team_name}：players={len(player_list)}, salaries={len(salary_list)}")

            for i in range(len(player_list)):
                all_rows.append({
                    'year': year,                    
                    'players': player_list[i],
                    'team': team_name,
                    'salary': salary_list[i]
                })

        except Exception as e:
            print(f"發生錯誤於 {team_name} {year}：{e}")

        time.sleep(random.uniform(1, 3))  # 輕微延遲，避免封鎖


    dirname = "nba_players_salary"
    if not os.path.exists(dirname):
        os.mkdir(dirname)

    df = pd.DataFrame(all_rows)
    df['team_cut'] = df["team"].str.split('-')
    df['team'] = df['team_cut'].str[-1]
    df.drop(columns=['team_cut'], inplace=True)
    df.index += 1
    fn = os.path.join(dirname, f"nba_players_salary_{year}.csv")
    # print(df)

    # 根據 "teams" 的值取得排序順序
    # df_sorted = df.sort_values(by='team', ignore_index=True)

    # save
    df.to_csv(fn, encoding="utf-8-sig")
    # with open('salary.json', 'w', encoding='utf-8') as f:
    #     json.dump(row, f, indent=4, ensure_ascii=False)

    return df

In [23]:
nba_players_salary(2024)

https://www.hoopshype.com/salaries/teams/atlanta-hawks/1/?season=2024
https://www.hoopshype.com/salaries/teams/boston-celtics/2/?season=2024
https://www.hoopshype.com/salaries/teams/brooklyn-nets/17/?season=2024
https://www.hoopshype.com/salaries/teams/charlotte-hornets/5312/?season=2024
https://www.hoopshype.com/salaries/teams/chicago-bulls/4/?season=2024
https://www.hoopshype.com/salaries/teams/cleveland-cavaliers/5/?season=2024
https://www.hoopshype.com/salaries/teams/dallas-mavericks/6/?season=2024
https://www.hoopshype.com/salaries/teams/denver-nuggets/7/?season=2024
https://www.hoopshype.com/salaries/teams/detroit-pistons/8/?season=2024
https://www.hoopshype.com/salaries/teams/golden-state-warriors/9/?season=2024
https://www.hoopshype.com/salaries/teams/houston-rockets/10/?season=2024
https://www.hoopshype.com/salaries/teams/indiana-pacers/11/?season=2024
https://www.hoopshype.com/salaries/teams/los-angeles-clippers/12/?season=2024
https://www.hoopshype.com/salaries/teams/los-angeles-lakers/13/?season=2024
https://www.hoopshype.com/salaries/teams/memphis-grizzlies/29/?season=2024
https://www.hoopshype.com/salaries/teams/miami-heat/14/?season=2024
https://www.hoopshype.com/salaries/teams/milwaukee-bucks/15/?season=2024
https://www.hoopshype.com/salaries/teams/minnesota-timberwolves/16/?season=2024
https://www.hoopshype.com/salaries/teams/new-orleans-pelicans/3/?season=2024
https://www.hoopshype.com/salaries/teams/new-york-knicks/18/?season=2024
https://www.hoopshype.com/salaries/teams/oklahoma-city-thunder/25/?season=2024
https://www.hoopshype.com/salaries/teams/orlando-magic/19/?season=2024
https://www.hoopshype.com/salaries/teams/philadelphia-76ers/20/?season=2024
https://www.hoopshype.com/salaries/teams/phoenix-suns/21/?season=2024
https://www.hoopshype.com/salaries/teams/portland-trail-blazers/22/?season=2024
https://www.hoopshype.com/salaries/teams/sacramento-kings/23/?season=2024
https://www.hoopshype.com/salaries/teams/san-antonio-spurs/24/?season=2024
https://www.hoopshype.com/salaries/teams/toronto-raptors/28/?season=2024
https://www.hoopshype.com/salaries/teams/utah-jazz/26/?season=2024
https://www.hoopshype.com/salaries/teams/washington-wizards/27/?season=2024

     year           players     team    salary
1    2024        Trae Young    hawks  43031940
2    2024      Clint Capela    hawks  22265280
3    2024      Caris LeVert    hawks  16615384
4    2024    Onyeka Okongwu    hawks  14000000
5    2024       Z. Risacher    hawks  12569040
..    ...               ...      ...       ...
612  2024           JT Thor  wizards    578577
613  2024  Tristan Vukcevic  wizards    578577
614  2024     Jaylen Martin  wizards    209114
615  2024     Jaylen Nowell  wizards    195147
616  2024   Jalen McDaniels  wizards    139391

[616 rows x 4 columns]